robot,settler,spaceship
kozosjavak/asteroidmining pull request #15
Opened 2021-03-20 22:59 UTC by Guby002

2021-03-20 23:01 UTC, Pucusta approved these changes

2021-03-21 01:02 UTC, ventt approved these changes

2021-03-21 01:09 UTC, ventt commented on src/classes/Settler.java
> +    public String GetType(){
Drill ele "@Override" es minden fgv ele ami az ososztalyban is van, csak maskepp valositja meg (Ha szukseges)

2021-03-21 01:09 UTC, ventt commented on src/classes/Settler.java
> +    public void Die(){};
Itt is override, szerintem

2021-03-21 01:10 UTC, ventt requested changes
Override-okat bekene cuccolgatni oda :D

2021-03-21 13:58 UTC, ventt approved these changes

2021-03-21 13:59 UTC, merged