BillOfMaterial implementation, Bills not needed, Material OK, closes #7
kozosjavak/asteroidmining pull request #16
Opened 2021-03-20 23:05 UTC by szalkusz

Bills-t kivettem, mert sztem nem kell.

2021-03-20 23:12 UTC, Pucusta submitted a review, later dismissed

2021-03-21 01:04 UTC, ventt requested changes
Szerintem holnap(Vasarnap) gondoljuk at a bill dolgot, hogy kell-e listaban tarolni mindenhol a bill-eket es azokat minden classnak tarolni. Szerintem lehet ra vmi statikusabb megoldast talalni.

2021-03-21 12:51 UTC, ventt approved these changes

2021-03-21 14:01 UTC, Pucusta reviewed
a misc.xml-t szerintem ne pushold fel

2021-03-21 14:09 UTC, ventt approved these changes

2021-03-21 14:13 UTC, Pucusta approved these changes

2021-03-21 14:13 UTC, merged